//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebL.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class webl
    {
        public int id { get; set; }

        [DisplayName("Name")]
        [Required(ErrorMessage = "Employee's name is required.")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Name field is limited between 2 and 50 characters")]
        //[RegularExpression(@"^[0-9a-zA-Z''-'\s]{1,40}$",  ErrorMessage = "Special characters are not allowed.")]
        public string name { get; set; }

        [DisplayName("Email")]
        [Required(ErrorMessage = "Employee's email is required.")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid email format")]
        [StringLength(50, ErrorMessage = "Email field is limited at 50 characters")]
        //[RegularExpression(@"^[0-9a-zA-Z''-'\s]{1,40}$",  ErrorMessage = "Special characters are not allowed.")]
        public string email { get; set; }

        [DisplayName("Address")]
        [StringLength(150, ErrorMessage = "Address field is limited at 150 characters")]
        //[RegularExpression(@"^[0-9a-zA-Z''-'\s]{1,40}$",  ErrorMessage = "Special characters are not allowed.")]
        public string address { get; set; }

        [DisplayName("Phone")]
        [Required(ErrorMessage = "Employee's phone is required.")]
        //[RegularExpression(@"^[0-9a-zA-Z''-'\s]{1,40}$",  ErrorMessage = "Special characters are not allowed.")]
        public string phone { get; set; }
    }
}
